### ISSUE TITLE
E-mail of the originator

### ISSUE THREAD

**Issue by AlexandderGorodetski** [mc-marcocheng/Machine-Learning-with-Numpy-only#5]
Hello @mc-marcocheng , I saw your comment in the K2 forum, and I understood that you were working on installation of K2 under windows. I know that this topic is not related to the current forum. Maybe you can share your email and we can discuss this issue personally. Or alternatively, could you please write directly to my email alexander.gorodetski@gmail.com

**Comment by mc-marcocheng** [comment]
https://github.com/k2-fsa/k2/issues/1256
